Set T-deck external notifications to false by default
meshtastic/defcontastic pull request #3
Opened 2024-07-30 17:32 UTC by loredous

(Third time's the charm, right?)

To protect the sanity of DefCon attendees, this change sets the notification on the T-deck to be disabled by default as requested in https://github.com/meshtastic/firmware/issues/4359

2024-07-30 22:19 UTC, thebentern commented
I would set this line in NodeDB.cpp to false instead. That should cover the T-Watch and T-Deck. Users will be able to turn it on after the fact with just enabling ext. notifications that way as well.
![image](https://github.com/user-attachments/assets/91cede73-147b-4e58-86a0-e7505727d484)

2024-07-30 22:41 UTC, thebentern requested changes
See main comment thread

2024-07-31 04:53 UTC, loredous commented
> I would set this line in NodeDB.cpp to false instead. That should cover the T-Watch and T-Deck. Users will be able to turn it on after the fact with just enabling ext. notifications that way as well. 

Addressed in updated commit. Moved changes to NodeDB

2024-07-31 11:00 UTC, thebentern approved these changes

2024-07-31 11:01 UTC, merged